service: MongoDB
configValidationMode: off

provider:
  name: openwhisk
  runtime: php

functions:
  getCollections:
    handler: action.getCollections
    name: MongoDB/getCollections
    events:
      - http: POST MongoDB/getCollections
  newCollection:
    handler: action.newCollection
    name: MongoDB/newCollection
    events:
      - http: POST MongoDB/newCollection

plugins:
  - serverless-openwhisk