service: MongoDB
configValidationMode: off

provider:
  name: openwhisk
  runtime: php

functions:
  getCollections:
    handler: action.getCollections
    name: MongoDB/getCollections
    events:
      - http: POST MongoDB/getCollections
  getCollection:
    handler: action.getCollection
    name: MongoDB/getCollection
    events:
      - http: POST MongoDB/getCollection
  newCollection:
    handler: action.newCollection
    name: MongoDB/newCollection
    events:
      - http: POST MongoDB/newCollection
  deleteCollection:
    handler: action.deleteCollection
    name: MongoDB/deleteCollection
    events:
      - http: POST MongoDB/deleteCollection
  removeDocument:
    handler: action.removeDocument
    name: MongoDB/removeDocument
    events:
      - http: POST MongoDB/removeDocument

plugins:
  - serverless-openwhisk