service: user
configValidationMode: off

provider:
  name: openwhisk
  runtime: php

functions:
  getToken:
    handler: login.getToken
    name: user/getToken
    events:
      - http: POST user/getToken
  checkToken:
    handler: login.checkToken
    name: user/checkToken
    events:
      - http: POST user/checkToken

  getallAttrs:
    handler: attributes.getAllAttrs
    name: user/getAllAttrs
    events:
      - http: POST user/getAllAttrs

plugins:
  - serverless-openwhisk