service: app
configValidationMode: off

provider:
  name: openwhisk
  runtime: php

functions:
  addKey:
    handler: management.addKey
    name: app/addKey
    events:
      - http: POST app/addKey
  addUser:
    handler: management.addUser
    name: app/addUser
    events:
      - http: POST app/addUser
  removeUser:
    handler: management.removeUser
    name: app/removeUser
    events:
      - http: POST app/removeUser
  getCredits:
    handler: management.getCredits
    name: app/getCredits
    events:
      - http: POST app/getCredits

plugins:
  - serverless-openwhisk
