service: database
configValidationMode: off

provider:
  name: openwhisk
  runtime: php

functions:
  addDB:
    handler: management.addDB
    name: database/addDB
    events:
      - http: POST database/addDB
  getDBList:
    handler: management.getDBList
    name: database/getDBList
    events:
      - http: POST database/listDB
  getPublicKey:
    handler: management.getPublicKey
    name: database/getPublicKey
    events:
      - http: POST database/publicKey

plugins:
  - serverless-openwhisk