service: DBManagement
configValidationMode: off

provider:
  name: openwhisk
  runtime: php

functions:
  addDB:
    handler: management.addDB
    name: DBManagement/addDB
    events:
      - http: POST DBManagement/addDB
  deleteDB:
    handler: management.deleteDB
    name: DBManagement/deleteDB
    events:
      - http: POST DBManagement/deleteDB
  getDBList:
    handler: management.getDBList
    name: DBManagement/getDBList
    events:
      - http: POST DBManagement/listDB
  getDBSettings:
    handler: management.getDBSettings
    name: DBManagement/getDBSettings
    events:
      - http: POST DBManagement/listDBSettings
  getPublicKey:
    handler: management.getPublicKey
    name: DBManagement/getPublicKey
    events:
      - http: POST DBManagement/publicKey

plugins:
  - serverless-openwhisk
